env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:react/recommended'
  - google
  - 'plugin:@typescript-eslint/recommended'
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
ignorePatterns:
  - node_modules/
  - dist/
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules:
  react/prop-types: off
  # '@typescript-eslint/no-unused-vars': error
  require-jsdoc: 0
  prettier/prettier:
    - error
